import asyncio
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context
from app.core.config import settings

# Alembic Config object
config = context.config

# Set up Python logging from alembic.ini
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Pull DATABASE_URL from the centralized settings object (reads .env / environment)
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

# Imported unguarded, on purpose. This used to sit in a `try/except
# ImportError` that fell back to `target_metadata = None`, so a typo in any
# model file produced an *empty* autogenerated migration instead of an error —
# a review would see a migration that does nothing and approve it.
from app.models import Base  # noqa: E402

target_metadata = Base.metadata


def include_object(obj, name, type_, reflected, compare_to):
    """
    Keep autogenerate away from the objects the models deliberately do not declare.

    A great deal of this schema is created in raw SQL by migrations and has no
    ORM counterpart: trigram and partial indexes, the soft-delete CHECKs, the
    two content-backup tables, and FK indexes the models omit on purpose —
    migration `102_order_items_product_id_idx` argues for exactly that and says
    so in its own docstring.

    None of it is drift. But `--autogenerate` cannot tell "the model does not
    declare this" from "this should not exist", so left alone it proposes
    dropping every one of them. Measured on 2026-08-23 against a real database
    at revision 137: 41 indexes, 30 constraints and 2 tables, including the
    trigram indexes the admin's order search runs on.

    So reflected objects the metadata does not know about are ignored, and a
    drop has to be written by hand — which is the right weight for dropping an
    index that production is using. That takes the same probe to 6 index drops
    and 2 constraint drops, and those are real: model and database disagree
    about a handful of index *names*, which is worth seeing.
    """
    if (
        reflected
        and compare_to is None
        and type_
        in {
            "index",
            "table",
            "unique_constraint",
            "foreign_key_constraint",
            "check_constraint",
        }
    ):
        return False
    return True


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_object=include_object,
        # Off by default, so a column that changed type in a model and not in
        # the database looked identical to one that had not.
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Run migrations in 'online' mode with async engine."""
    configuration = config.get_section(config.config_ini_section, {})
    connectable = async_engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
