#!/usr/bin/env bash
# Sequential blue-green cutover of api then pos-api behind nginx.
#
# Starts the idle colour on the new :latest image, waits until /health
# succeeds with the production Host header, retargets nginx via
# nginx/runtime/upstreams.conf, drains keepalive, then docker-stops the
# old colour. Never --force-recreate: that is the stop-then-start hole
# this exists to close.
#
# Subcommands:
#   (none)               cut over api, then pos-api
#   restore-upstreams    rewrite upstreams.conf from .deploy-slot
#                        (git reset restores the committed default, which
#                        still points at slot A even after a green cutover)
set -euo pipefail

DEPLOY_DIR="${DEPLOY_DIR:-/opt/melting-moments-cakes}"
COMPOSE_FILE="${COMPOSE_FILE:-docker-compose.prod.yml}"
SLOT_FILE="${SLOT_FILE:-$DEPLOY_DIR/.deploy-slot}"
UPSTREAMS_FILE="${UPSTREAMS_FILE:-$DEPLOY_DIR/nginx/runtime/upstreams.conf}"
WARM_LOCK="${WARM_LOCK:-/tmp/mm-aggregator-warm.lock}"
# Must match keepalive_timeout in nginx/runtime/upstreams.conf.
DRAIN_SECONDS="${DRAIN_SECONDS:-5}"
STOP_GRACE="${STOP_GRACE:-10}"
WAIT_TIMEOUT="${WAIT_TIMEOUT:-90}"
HEALTH_ATTEMPTS="${HEALTH_ATTEMPTS:-10}"

API_HOST="${API_HOST:-api.meltingmomentscakes.com}"
POS_HOST="${POS_HOST:-pos.meltingmomentscakes.com}"

cd "$DEPLOY_DIR"

_compose() {
  # Every docker invocation needs stdin closed: this script is often piped
  # into `bash -s` from GitHub Actions, and docker reads stdin, so a command
  # without the redirect swallows the rest of the script.
  # `--profile green` so `ps`/`exec`/`logs` see api-green even though that
  # service is not in the default `up` set.
  docker compose -f "$COMPOSE_FILE" --profile green "$@" < /dev/null
}

_die() {
  echo "ERROR: $*" >&2
  exit 1
}

_load_slots() {
  API_LIVE=api
  POS_LIVE=pos-api
  if [ -f "$SLOT_FILE" ]; then
    while IFS='=' read -r key value || [ -n "${key:-}" ]; do
      [ -z "${key:-}" ] && continue
      case "$key" in
        \#*) continue ;;
        api) API_LIVE=$value ;;
        pos-api) POS_LIVE=$value ;;
      esac
    done < "$SLOT_FILE"
  fi
  case "$API_LIVE" in
    api|api-green) ;;
    *) _die "invalid api slot in $SLOT_FILE: $API_LIVE" ;;
  esac
  case "$POS_LIVE" in
    pos-api|pos-api-green) ;;
    *) _die "invalid pos-api slot in $SLOT_FILE: $POS_LIVE" ;;
  esac
}

_idle_for() {
  case "$1" in
    api) if [ "$API_LIVE" = api ]; then echo api-green; else echo api; fi ;;
    pos-api) if [ "$POS_LIVE" = pos-api ]; then echo pos-api-green; else echo pos-api; fi ;;
    *) _die "unknown pair $1" ;;
  esac
}

_write_upstreams() {
  local tmp="${UPSTREAMS_FILE}.tmp"
  mkdir -p "$(dirname "$UPSTREAMS_FILE")"
  cat > "$tmp" <<EOF
# Generated by scripts/cutover-backend.sh — live api=${API_LIVE} pos-api=${POS_LIVE}
# keepalive_timeout must stay in sync with DRAIN_SECONDS in that script.
upstream api_backend {
    server ${API_LIVE}:8000;
    keepalive 32;
    keepalive_timeout 5s;
    keepalive_requests 1000;
}

upstream pos_backend {
    server ${POS_LIVE}:8000;
    keepalive 32;
    keepalive_timeout 5s;
    keepalive_requests 1000;
}
EOF
  mv "$tmp" "$UPSTREAMS_FILE"
}

_write_slot_file() {
  cat > "$SLOT_FILE" <<EOF
api=${API_LIVE}
pos-api=${POS_LIVE}
EOF
}

restore_upstreams() {
  _load_slots
  _write_upstreams
  echo "Restored $UPSTREAMS_FILE → api=${API_LIVE} pos-api=${POS_LIVE}"
}

_running() {
  local id
  id=$(_compose ps -q --status running "$1" 2>/dev/null || true)
  [ -n "$id" ]
}

_aggregator_worker_ids() {
  docker ps -q --filter "name=aggregator-worker" < /dev/null || true
}

_stop_aggregator_workers() {
  local ids
  ids=$(_aggregator_worker_ids)
  [ -n "$ids" ] || return 0
  echo "==> Stopping one-shot aggregator-worker so cutover has RAM..."
  echo "    $ids"
  # heal-sessions / warm-sessions are cron one-shots, not a daemon. A half-
  # finished login stays `needs_bootstrap` and the next */2 min tick retries.
  # Waiting them out held the deploy for up to 20 minutes (and a dead Talabat
  # login used to hold the warm lock for 45). SIGTERM the container; compose
  # `--rm` then exits and drops the flock this script is about to take.
  # shellcheck disable=SC2086
  docker stop -t 15 $ids < /dev/null || true
}

_wait_for_aggregator_idle() {
  _stop_aggregator_workers

  if command -v flock >/dev/null 2>&1; then
    mkdir -p "$(dirname "$WARM_LOCK")"
    # World-writable: cron runs as root and creates this first otherwise, and
    # a 644 root:root file is what made cutover print "Permission denied" and
    # continue without the lock — so heal-sessions could start Chrome mid-cutover.
    touch "$WARM_LOCK" 2>/dev/null || true
    chmod 666 "$WARM_LOCK" 2>/dev/null || true
    exec 9>"$WARM_LOCK" || {
      echo "WARNING: cannot open $WARM_LOCK — continuing without flock"
      _stop_aggregator_workers
      return 0
    }
    echo "==> Acquiring $WARM_LOCK so cron cannot start Chrome during cutover..."
    if ! flock -w 30 9; then
      echo "    lock still held after stop; stopping workers again and retrying"
      _stop_aggregator_workers
      if ! flock -w 30 9; then
        _die "could not acquire $WARM_LOCK after stopping aggregator-worker"
      fi
    fi
    echo "    acquired $WARM_LOCK (held until this script exits)"
  else
    echo "    flock not available — worker stop only"
  fi

  # A heal tick may have started between the first stop and flock.
  _stop_aggregator_workers
}

_wait_health() {
  local svc=$1 host=$2 i
  echo "==> Waiting for $svc /health (Host: $host)..."
  for i in $(seq 1 "$HEALTH_ATTEMPTS"); do
    if _compose exec -T "$svc" \
      curl -sf -H "Host: $host" "http://localhost:8000/health" \
      >/dev/null 2>&1; then
      echo "    $svc /health is ok"
      return 0
    fi
    echo "    waiting... (${i}/${HEALTH_ATTEMPTS})"
    sleep 1
  done
  echo "ERROR: $svc failed /health. Container logs:" >&2
  _compose logs --tail=50 "$svc" || true
  return 1
}

_stop_slot() {
  local svc=$1 cid
  cid=$(_compose ps -q --status running "$svc" 2>/dev/null || true)
  if [ -z "$cid" ]; then
    echo "    $svc is already stopped"
    return 0
  fi
  echo "==> docker stop -t ${STOP_GRACE} $svc ($cid)"
  docker stop -t "$STOP_GRACE" "$cid" < /dev/null
  # restart: always on a stopped container would bring it back on daemon
  # reboot, overlapping the live colour. Pin the idle slot down.
  docker update --restart=no "$cid" < /dev/null || true
}

_both_running() {
  _running "$1" && _running "$2"
}

_abort_switch() {
  local idle=$1 live=$2 blue=$3 reason=$4
  echo "ERROR: $reason" >&2
  if [ "$blue" = api ]; then
    API_LIVE=$live
  else
    POS_LIVE=$live
  fi
  _write_upstreams
  _compose exec -T nginx nginx -s reload || true
  _stop_slot "$idle"
  exit 1
}

_cutover_pair() {
  local blue=$1 green=$2 host=$3
  local live idle backup
  if [ "$blue" = api ]; then
    live=$API_LIVE
  else
    live=$POS_LIVE
  fi
  idle=$(_idle_for "$blue")

  echo ""
  echo "==> Cutting over $blue ($live → $idle)"

  echo "==> Starting idle slot $idle with the current :latest image..."
  # A failed start must not leave the idle colour running next to live —
  # that is the extra API this box OOMs on.
  if ! _compose up -d --no-deps --wait --wait-timeout "$WAIT_TIMEOUT" "$idle"; then
    echo "ERROR: $idle failed compose --wait. Container logs:" >&2
    _compose logs --tail=50 "$idle" || true
    _stop_slot "$idle"
    _die "idle slot $idle failed to become healthy in time"
  fi

  if ! _wait_health "$idle" "$host"; then
    _stop_slot "$idle"
    _die "$idle failed /health; stopped it so both colours are not left running"
  fi

  backup="${UPSTREAMS_FILE}.bak"
  cp "$UPSTREAMS_FILE" "$backup"
  if [ "$blue" = api ]; then
    API_LIVE=$idle
  else
    POS_LIVE=$idle
  fi
  _write_upstreams
  if ! _compose exec -T nginx nginx -t; then
    mv "$backup" "$UPSTREAMS_FILE"
    _abort_switch "$idle" "$live" "$blue" "nginx -t failed; restored previous upstreams and stopping $idle"
  fi
  if ! _compose exec -T nginx nginx -s reload; then
    mv "$backup" "$UPSTREAMS_FILE"
    _abort_switch "$idle" "$live" "$blue" "nginx reload failed; restored previous upstreams and stopping $idle"
  fi
  rm -f "$backup"

  echo "==> Probing https://${host}/health through nginx..."
  # Retry, and force HTTP/1.1. The first HTTPS request straight after
  # `nginx -s reload` races the reload: over HTTP/2 that surfaced intermittently as
  # `curl: (16) Error in the HTTP2 framing layer`, which twice rolled back an
  # otherwise-healthy deploy (the new slot was already `/health`-ok on 8000 and
  # nginx -t/-reload had both passed). `--http1.1` removes the HTTP/2 framing race
  # entirely — the probe only needs to prove nginx routes to a live upstream, not to
  # exercise HTTP/2 — and the loop rides out any other momentary blip (a 502 while
  # nginx finishes swapping upstreams, a reset). A genuine fault still fails every
  # attempt: app down → 502 each time, wrong Host → 400 each time, so it aborts.
  code="curl-fail"
  for _attempt in 1 2 3 4 5; do
    code=$(curl -sS --http1.1 --max-time 15 \
      --resolve "${host}:443:127.0.0.1" \
      -o /dev/null -w "%{http_code}" \
      "https://${host}/health") || code="curl-fail"
    [ "$code" = "200" ] && break
    if [ "$_attempt" -lt 5 ]; then
      echo "    probe attempt ${_attempt}/5: ${code} — retrying in 2s..."
      sleep 2
    fi
  done
  if [ "$code" != "200" ]; then
    _abort_switch "$idle" "$live" "$blue" \
      "https://${host}/health returned HTTP ${code} after reload and 5 attempts (want 200). A TrustedHost 400 means the Host header is wrong; a 502 means nginx is still pointing at a down slot."
  fi
  echo "    https://${host}/health → 200"

  echo "==> Draining $live (${DRAIN_SECONDS}s keepalive_timeout)..."
  sleep "$DRAIN_SECONDS"

  _stop_slot "$live"

  if _both_running "$blue" "$green"; then
    _die "both $blue and $green are still running after drain — extra API RAM on this box is how it OOMs"
  fi
  if ! _running "$idle"; then
    _die "$idle is not running after cutover"
  fi
  if _running "$live"; then
    _die "$live is still running after docker stop"
  fi

  _write_slot_file
  echo "    live slots: api=${API_LIVE} pos-api=${POS_LIVE}"
}

cutover() {
  _wait_for_aggregator_idle
  _load_slots
  echo "==> Current live slots: api=${API_LIVE} pos-api=${POS_LIVE}"
  _cutover_pair api api-green "$API_HOST"
  _cutover_pair pos-api pos-api-green "$POS_HOST"
  echo ""
  echo "==> Cutover complete. Live: api=${API_LIVE} pos-api=${POS_LIVE}"
  _compose ps
}

case "${1:-}" in
  restore-upstreams) restore_upstreams ;;
  ""|cutover) cutover ;;
  *)
    echo "Usage: $0 [cutover|restore-upstreams]" >&2
    exit 2
    ;;
esac
