"""Add privacy policy CMS page with EN and AR content

Revision ID: 010_cms_privacy_page
Revises: 009_cms_arabic_seed
Create Date: 2026-03-06 00:00:00.000000

"""

import json
import uuid
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "010_cms_privacy_page"
down_revision: Union[str, None] = "009_cms_arabic_seed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ── Content ───────────────────────────────────────────────────────────────────

PRIVACY_EN = {
    "header": {
        "title": "Privacy Policy",
        "subtitle": "Last updated: March 2025",
    },
    "intro": (
        "This Privacy Policy describes Our policies and procedures on the collection, use and "
        "disclosure of Your information when You use the Service and tells You about Your privacy "
        "rights and how the law protects You.\n\n"
        "We use Your Personal data to provide and improve the Service. By using the Service, You "
        "agree to the collection and use of information in accordance with this Privacy Policy."
    ),
    "sections": [
        {
            "title": "Interpretation and Definitions",
            "body": (
                "The words of which the initial letter is capitalized have meanings defined under "
                "the following conditions. The following definitions shall have the same meaning "
                "regardless of whether they appear in singular or in plural.\n\n"
                "Account means a unique account created for You to access our Service or parts of our Service.\n\n"
                'Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) '
                "refers to Melting Moments Cakes, GARDEN TOWER 21 ARAB CULTURAL ST. SHOP NO. 2, "
                "AL MAJAZ 3, SHARJAH, UNITED ARAB EMIRATES.\n\n"
                "Cookies are small files that are placed on Your computer, mobile device or any other device "
                "by a website, containing the details of Your browsing history on that website among its many uses.\n\n"
                "Country refers to: United Arab Emirates\n\n"
                "Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.\n\n"
                "Personal Data is any information that relates to an identified or identifiable individual.\n\n"
                "Service refers to the Website.\n\n"
                "Service Provider means any natural or legal person who processes the data on behalf of the Company. "
                "It refers to third-party companies or individuals employed by the Company to facilitate the Service, "
                "to provide the Service on behalf of the Company, to perform services related to the Service or to "
                "assist the Company in analyzing how the Service is used.\n\n"
                "Usage Data refers to data collected automatically, either generated by the use of the Service or "
                "from the Service infrastructure itself (for example, the duration of a page visit).\n\n"
                "Website refers to Melting Moments Cakes, accessible from www.meltingmomentscakes.com\n\n"
                "You means the individual accessing or using the Service, or the company, or other legal entity "
                "on behalf of which such individual is accessing or using the Service, as applicable."
            ),
        },
        {
            "title": "Collecting and Using Your Personal Data",
            "body": (
                "While using Our Service, We may ask You to provide Us with certain personally identifiable "
                "information that can be used to contact or identify You. Personally identifiable information "
                "may include, but is not limited to:\n\n"
                "• Email address\n"
                "• First name and last name\n"
                "• Phone number\n"
                "• Address, State, Province, ZIP/Postal code, City\n\n"
                "Usage Data is collected automatically when using the Service. Usage Data may include information "
                "such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, "
                "the pages of our Service that You visit, the time and date of Your visit, the time spent on those "
                "pages, unique device identifiers and other diagnostic data.\n\n"
                "When You access the Service by or through a mobile device, We may collect certain information "
                "automatically, including, but not limited to, the type of mobile device You use, Your mobile device "
                "unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile "
                "Internet browser You use, unique device identifiers and other diagnostic data.\n\n"
                "We may also collect information that Your browser sends whenever You visit our Service or when You "
                "access the Service by or through a mobile device."
            ),
        },
        {
            "title": "Tracking Technologies and Cookies",
            "body": (
                "We use Cookies and similar tracking technologies to track the activity on Our Service and store "
                "certain information. Tracking technologies used are beacons, tags, and scripts to collect and track "
                "information and to improve and analyze Our Service.\n\n"
                "Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your "
                "browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not "
                "accept Cookies, You may not be able to use some parts of our Service.\n\n"
                "Flash Cookies. Certain features of our Service may use local stored objects (or Flash Cookies) to "
                "collect and store information about Your preferences or Your activity on our Service. Flash Cookies "
                "are not managed by the same browser settings as those used for Browser Cookies.\n\n"
                "Web Beacons. Certain sections of our Service and our emails may contain small electronic files known "
                "as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the "
                "Company, for example, to count users who have visited those pages or opened an email and for other "
                "related website statistics.\n\n"
                "We use both Session and Persistent Cookies for the following purposes:\n\n"
                "Necessary / Essential Cookies (Session) — These Cookies are essential to provide You with services "
                "available through the Website and to enable You to use some of its features. They help to "
                "authenticate users and prevent fraudulent use of user accounts.\n\n"
                "Cookies Policy / Notice Acceptance Cookies (Persistent) — These Cookies identify if users have "
                "accepted the use of cookies on the Website.\n\n"
                "Functionality Cookies (Persistent) — These Cookies allow us to remember choices You make when You "
                "use the Website, such as remembering your login details or language preference."
            ),
        },
        {
            "title": "Use of Your Personal Data",
            "body": (
                "The Company may use Personal Data for the following purposes:\n\n"
                "• To provide and maintain our Service, including to monitor the usage of our Service.\n"
                "• To manage Your Account: to manage Your registration as a user of the Service.\n"
                "• For the performance of a contract: the development, compliance and undertaking of the "
                "purchase contract for the products, items or services You have purchased.\n"
                "• To contact You: by email, telephone calls, SMS, or other equivalent forms of electronic "
                "communication regarding updates or informative communications related to the functionalities, "
                "products or contracted services.\n"
                "• To provide You with news, special offers and general information about other goods, services "
                "and events which we offer that are similar to those that you have already purchased or enquired about.\n"
                "• To manage Your requests: To attend and manage Your requests to Us.\n"
                "• For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, "
                "restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.\n"
                "• For other purposes: such as data analysis, identifying usage trends, determining the effectiveness "
                "of our promotional campaigns and to evaluate and improve our Service.\n\n"
                "We may share Your personal information in the following situations:\n\n"
                "• With Service Providers: to monitor and analyze the use of our Service, to contact You.\n"
                "• For business transfers: in connection with any merger, sale of company assets, financing, or "
                "acquisition of all or a portion of Our business.\n"
                "• With Affiliates: in which case we will require those affiliates to honor this Privacy Policy.\n"
                "• With business partners: to offer You certain products, services, or promotions.\n"
                "• With Your Consent: We may disclose Your personal information for any other purpose with Your consent."
            ),
        },
        {
            "title": "Retention of Your Personal Data",
            "body": (
                "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out "
                "in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply "
                "with our legal obligations (for example, if we are required to retain your data to comply with "
                "applicable laws), resolve disputes, and enforce our legal agreements and policies.\n\n"
                "The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally "
                "retained for a shorter period of time, except when this data is used to strengthen the security or "
                "to improve the functionality of Our Service, or We are legally obligated to retain this data for "
                "longer time periods."
            ),
        },
        {
            "title": "Transfer of Your Personal Data",
            "body": (
                "Your information, including Personal Data, is processed at the Company's operating offices and in "
                "any other places where the parties involved in the processing are located. It means that this "
                "information may be transferred to — and maintained on — computers located outside of Your state, "
                "province, country, or other governmental jurisdiction where the data protection laws may differ "
                "from those from Your jurisdiction.\n\n"
                "Your consent to this Privacy Policy followed by Your submission of such information represents Your "
                "agreement to that transfer.\n\n"
                "The Company will take all steps reasonably necessary to ensure that Your data is treated securely "
                "and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to "
                "an organization or a country unless there are adequate controls in place including the security of "
                "Your data and other personal information."
            ),
        },
        {
            "title": "Disclosure of Your Personal Data",
            "body": (
                "Business Transactions: If the Company is involved in a merger, acquisition, or asset sale, Your "
                "Personal Data may be transferred. We will provide notice before Your Personal Data is transferred "
                "and becomes subject to a different Privacy Policy.\n\n"
                "Law Enforcement: Under certain circumstances, the Company may be required to disclose Your Personal "
                "Data if required to do so by law or in response to valid requests by public authorities (e.g. a "
                "court or a government agency).\n\n"
                "Other Legal Requirements: The Company may disclose Your Personal Data in the good faith belief that "
                "such action is necessary to:\n\n"
                "• Comply with a legal obligation\n"
                "• Protect and defend the rights or property of the Company\n"
                "• Prevent or investigate possible wrongdoing in connection with the Service\n"
                "• Protect the personal safety of users of the Service or the public\n"
                "• Protect against legal liability"
            ),
        },
        {
            "title": "Security of Your Personal Data",
            "body": (
                "The security of Your Personal Data is important to Us, but remember that no method of transmission "
                "over the Internet or method of electronic storage is 100% secure. While We strive to use "
                "commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security."
            ),
        },
        {
            "title": "Links to Other Websites",
            "body": (
                "Our Service may contain links to other websites that are not operated by Us. If You click on a "
                "third-party link, You will be directed to that third party's site. We strongly advise You to review "
                "the Privacy Policy of every site You visit.\n\n"
                "We have no control over and assume no responsibility for the content, privacy policies, or practices "
                "of any third-party sites or services."
            ),
        },
        {
            "title": "Changes to this Privacy Policy",
            "body": (
                "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting "
                "the new Privacy Policy on this page.\n\n"
                "We will let You know via email and/or a prominent notice on Our Service, prior to the change "
                "becoming effective.\n\n"
                "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy "
                "Policy are effective when they are posted on this page."
            ),
        },
    ],
    "contact": {
        "email": "meltingmomentscakes@gmail.com",
        "phone": "+971 50 368 7757",
    },
    "seo": {
        "title": "Privacy Policy",
        "description": "Privacy policy for Melting Moments Cakes — how we collect, use and protect your personal data.",
    },
}

PRIVACY_AR = {
    "header": {
        "title": "سياسة الخصوصية",
        "subtitle": "آخر تحديث: مارس 2025",
    },
    "intro": (
        "تصف سياسة الخصوصية هذه سياساتنا وإجراءاتنا المتعلقة بجمع معلوماتك واستخدامها والإفصاح عنها عند استخدامك "
        "للخدمة، وتُطلعك على حقوق خصوصيتك وكيفية حماية القانون لها.\n\n"
        "نستخدم بياناتك الشخصية لتقديم الخدمة وتحسينها. باستخدامك للخدمة، فإنك توافق على جمع المعلومات "
        "واستخدامها وفقاً لسياسة الخصوصية هذه."
    ),
    "sections": [
        {
            "title": "التفسير والتعريفات",
            "body": (
                "الكلمات التي تبدأ بحرف كبير لها معانٍ محددة وفق الشروط التالية. تحمل التعريفات التالية المعنى ذاته "
                "سواء وردت بصيغة المفرد أو الجمع.\n\n"
                "الحساب يعني حساباً فريداً يُنشأ لك للوصول إلى خدمتنا أو أجزاء منها.\n\n"
                'الشركة (المشار إليها بـ "الشركة" أو "نحن" أو "لنا" أو "خاصتنا" في هذه الاتفاقية) تعني '
                "ملتينج مومنتس كيكس، برج جاردن 21، شارع الثقافة العربية، محل رقم 2، الماجز 3، الشارقة، "
                "الإمارات العربية المتحدة.\n\n"
                "ملفات تعريف الارتباط (الكوكيز) هي ملفات صغيرة تُوضع على جهاز الكمبيوتر أو الجهاز المحمول أو أي "
                "جهاز آخر بواسطة موقع ويب، وتحتوي على تفاصيل سجل تصفحك على ذلك الموقع من بين استخداماتها العديدة.\n\n"
                "البلد يشير إلى: الإمارات العربية المتحدة\n\n"
                "الجهاز يعني أي جهاز يمكنه الوصول إلى الخدمة كالكمبيوتر أو الهاتف المحمول أو الجهاز اللوحي.\n\n"
                "البيانات الشخصية هي أي معلومات تتعلق بفرد محدد الهوية أو قابل للتحديد.\n\n"
                "الخدمة تشير إلى الموقع الإلكتروني.\n\n"
                "مزود الخدمة يعني أي شخص طبيعي أو اعتباري يعالج البيانات نيابةً عن الشركة، ويشمل الشركات أو "
                "الأفراد الخارجيين الذين توظفهم الشركة لتيسير الخدمة أو تقديمها نيابةً عنها.\n\n"
                "بيانات الاستخدام تشير إلى البيانات التي تُجمع تلقائياً، سواء أُنشئت من استخدام الخدمة أو من "
                "البنية التحتية للخدمة ذاتها (مثلاً: مدة زيارة الصفحة).\n\n"
                "الموقع الإلكتروني يشير إلى ملتينج مومنتس كيكس، المتاح على www.meltingmomentscakes.com\n\n"
                "أنت يعني الفرد الذي يصل إلى الخدمة أو يستخدمها، أو الشركة أو أي كيان قانوني آخر يصل إليها "
                "نيابةً عنه، بحسب الانطباق."
            ),
        },
        {
            "title": "جمع بياناتك الشخصية واستخدامها",
            "body": (
                "أثناء استخدامك لخدمتنا، قد نطلب منك تقديم معلومات تعريفية شخصية يمكن استخدامها للتواصل معك أو "
                "التعرف عليك. قد تشمل هذه المعلومات، على سبيل المثال لا الحصر:\n\n"
                "• عنوان البريد الإلكتروني\n"
                "• الاسم الأول والأخير\n"
                "• رقم الهاتف\n"
                "• العنوان والمنطقة والمدينة والرمز البريدي\n\n"
                "تُجمع بيانات الاستخدام تلقائياً عند استخدام الخدمة. وقد تشمل معلومات مثل عنوان بروتوكول الإنترنت "
                "لجهازك (عنوان IP)، ونوع المتصفح وإصداره، وصفحات الخدمة التي تزورها، ووقت وتاريخ زيارتك، والوقت "
                "الذي تقضيه في تلك الصفحات، ومعرّفات الجهاز الفريدة وبيانات تشخيصية أخرى.\n\n"
                "عند وصولك إلى الخدمة عبر جهاز محمول، قد نجمع معلومات معينة تلقائياً، بما في ذلك نوع الجهاز "
                "المحمول، ومعرّف الجهاز الفريد، وعنوان IP للجهاز، ونظام التشغيل المحمول، ونوع متصفح الإنترنت "
                "المحمول الذي تستخدمه."
            ),
        },
        {
            "title": "تقنيات التتبع وملفات تعريف الارتباط",
            "body": (
                "نستخدم ملفات تعريف الارتباط وتقنيات التتبع المماثلة لتتبع النشاط على خدمتنا وتخزين معلومات معينة. "
                "تشمل تقنيات التتبع المستخدمة إشارات الويب والعلامات والسكريبتات.\n\n"
                "ملفات تعريف الارتباط (كوكيز المتصفح): ملف صغير يُوضع على جهازك. يمكنك توجيه متصفحك لرفض جميع "
                "الكوكيز أو للإشارة عند إرسال كوكي. ومع ذلك، إذا لم تقبل الكوكيز، فقد لا تتمكن من استخدام بعض "
                "أجزاء خدمتنا.\n\n"
                "كوكيز فلاش: قد تستخدم بعض ميزات خدمتنا كائنات مخزّنة محلياً (كوكيز فلاش) لجمع معلومات "
                "حول تفضيلاتك أو نشاطك. لا تُدار كوكيز فلاش بنفس إعدادات المتصفح المستخدمة لكوكيز المتصفح.\n\n"
                "إشارات الويب: قد تحتوي بعض أقسام خدمتنا ورسائلنا الإلكترونية على ملفات إلكترونية صغيرة تُعرف "
                "بإشارات الويب تُتيح للشركة إحصاء المستخدمين الذين زاروا تلك الصفحات أو فتحوا رسالة إلكترونية.\n\n"
                "نستخدم كلاً من الكوكيز الجلسية والدائمة للأغراض التالية:\n\n"
                "الكوكيز الضرورية / الأساسية (جلسية) — ضرورية لتزويدك بالخدمات المتاحة عبر الموقع وتمكينك من "
                "استخدام بعض ميزاته، وتساعد في مصادقة المستخدمين ومنع الاستخدام الاحتيالي.\n\n"
                "كوكيز قبول سياسة الكوكيز (دائمة) — تُحدد ما إذا كان المستخدمون قد وافقوا على استخدام الكوكيز.\n\n"
                "كوكيز الوظائف (دائمة) — تُتيح لنا تذكّر الخيارات التي تتخذها عند استخدام الموقع، كتذكر "
                "بيانات تسجيل الدخول أو تفضيل اللغة."
            ),
        },
        {
            "title": "استخدام بياناتك الشخصية",
            "body": (
                "قد تستخدم الشركة البيانات الشخصية للأغراض التالية:\n\n"
                "• لتقديم خدمتنا والحفاظ عليها، بما في ذلك مراقبة استخدامها.\n"
                "• لإدارة حسابك: إدارة تسجيلك كمستخدم للخدمة.\n"
                "• لتنفيذ عقد: تطوير عقد الشراء والالتزام به فيما يخص المنتجات أو الخدمات التي اشتريتها.\n"
                "• للتواصل معك: عبر البريد الإلكتروني أو المكالمات الهاتفية أو الرسائل النصية أو أشكال التواصل "
                "الإلكتروني الأخرى بشأن التحديثات أو المعلومات المتعلقة بالخدمات المتعاقد عليها.\n"
                "• لتزويدك بالأخبار والعروض الخاصة ومعلومات عامة حول سلع وخدمات وفعاليات أخرى مشابهة لما اشتريته "
                "أو استفسرت عنه سابقاً.\n"
                "• لإدارة طلباتك: معالجة طلباتك الموجهة إلينا والرد عليها.\n"
                "• لأغراض العمليات التجارية: قد نستخدم معلوماتك لتقييم عمليات الاندماج أو البيع أو نقل الأصول.\n"
                "• لأغراض أخرى: كتحليل البيانات وتحديد اتجاهات الاستخدام وتقييم فعالية حملاتنا الترويجية.\n\n"
                "قد نشارك معلوماتك الشخصية في الحالات التالية:\n\n"
                "• مع مزودي الخدمة: لمراقبة وتحليل استخدام خدمتنا.\n"
                "• في عمليات الأعمال: في سياق أي اندماج أو بيع أصول أو استحواذ.\n"
                "• مع الشركات التابعة: مع اشتراط الالتزام بسياسة الخصوصية هذه.\n"
                "• مع الشركاء التجاريين: لتقديم منتجات أو خدمات أو عروض ترويجية معينة.\n"
                "• بموافقتك: قد نفصح عن معلوماتك الشخصية لأي غرض آخر بموافقتك."
            ),
        },
        {
            "title": "الاحتفاظ ببياناتك الشخصية",
            "body": (
                "ستحتفظ الشركة ببياناتك الشخصية فقط طالما كان ذلك ضرورياً للأغراض المنصوص عليها في سياسة "
                "الخصوصية هذه. سنحتفظ ببياناتك الشخصية ونستخدمها بالقدر اللازم للامتثال لالتزاماتنا القانونية "
                "وحسم النزاعات وإنفاذ اتفاقياتنا وسياساتنا القانونية.\n\n"
                "ستحتفظ الشركة أيضاً ببيانات الاستخدام لأغراض التحليل الداخلي. تُحتفظ ببيانات الاستخدام عموماً "
                "لفترة أقصر، إلا إذا استُخدمت لتعزيز أمن الخدمة أو تحسين وظائفها، أو إذا كنا ملزمين قانونياً "
                "بالاحتفاظ بها لفترات أطول."
            ),
        },
        {
            "title": "نقل بياناتك الشخصية",
            "body": (
                "تُعالَج معلوماتك، بما فيها البيانات الشخصية، في مكاتب تشغيل الشركة وفي أي أماكن أخرى يتواجد "
                "فيها الأطراف المشاركون في المعالجة. يعني ذلك أن هذه المعلومات قد تُنقل إلى أجهزة كمبيوتر خارج "
                "ولايتك القضائية، حيث قد تختلف قوانين حماية البيانات.\n\n"
                "موافقتك على سياسة الخصوصية هذه تليها تقديمك لهذه المعلومات تمثل موافقتك على هذا النقل.\n\n"
                "ستتخذ الشركة جميع الخطوات المعقولة لضمان معالجة بياناتك بأمان وفقاً لهذه السياسة، ولن يتم نقل "
                "أي بيانات شخصية إلى منظمة أو دولة ما لم تكن هناك ضوابط كافية لضمان أمان بياناتك."
            ),
        },
        {
            "title": "الإفصاح عن بياناتك الشخصية",
            "body": (
                "المعاملات التجارية: إذا كانت الشركة طرفاً في اندماج أو استحواذ أو بيع أصول، فقد يتم نقل بياناتك "
                "الشخصية. سنخطرك قبل نقل بياناتك وإخضاعها لسياسة خصوصية مختلفة.\n\n"
                "إنفاذ القانون: في ظروف معينة، قد تُلزَم الشركة بالإفصاح عن بياناتك الشخصية إذا طُلب منها ذلك "
                "بموجب القانون أو استجابةً لطلبات مشروعة من السلطات العامة.\n\n"
                "المتطلبات القانونية الأخرى: قد تفصح الشركة عن بياناتك الشخصية بحسن نية عندما يكون ذلك ضرورياً:\n\n"
                "• للامتثال لالتزام قانوني\n"
                "• لحماية حقوق الشركة أو ممتلكاتها والدفاع عنها\n"
                "• لمنع أو التحقيق في مخالفات محتملة تتعلق بالخدمة\n"
                "• لحماية السلامة الشخصية لمستخدمي الخدمة أو الجمهور\n"
                "• للحماية من المسؤولية القانونية"
            ),
        },
        {
            "title": "أمن بياناتك الشخصية",
            "body": (
                "أمن بياناتك الشخصية أمر مهم لنا، غير أنه تجدر الإشارة إلى أنه لا توجد طريقة نقل عبر الإنترنت "
                "أو طريقة تخزين إلكترونية آمنة بنسبة 100%. بينما نسعى إلى استخدام وسائل مقبولة تجارياً لحماية "
                "بياناتك الشخصية، لا يمكننا ضمان أمانها المطلق."
            ),
        },
        {
            "title": "روابط المواقع الأخرى",
            "body": (
                "قد تحتوي خدمتنا على روابط لمواقع أخرى لا تديرها. إذا نقرت على رابط طرف ثالث، فستُوجَّه إلى "
                "موقع ذلك الطرف. ننصحك بشدة بمراجعة سياسة الخصوصية لكل موقع تزوره.\n\n"
                "ليس لدينا سيطرة على محتوى سياسات الخصوصية أو ممارسات أي مواقع أو خدمات تابعة لطرف ثالث، "
                "ولا نتحمل أي مسؤولية تجاهها."
            ),
        },
        {
            "title": "التغييرات على سياسة الخصوصية هذه",
            "body": (
                "قد نُحدّث سياسة الخصوصية هذه من وقت لآخر. سنُعلمك بأي تغييرات عبر نشر سياسة الخصوصية الجديدة "
                "على هذه الصفحة.\n\n"
                "سنُبلّغك عبر البريد الإلكتروني و/أو إشعار بارز على خدمتنا قبل سريان التغيير.\n\n"
                "يُنصح بمراجعة سياسة الخصوصية هذه دورياً للاطلاع على أي تغييرات. تسري التغييرات فور نشرها "
                "على هذه الصفحة."
            ),
        },
    ],
    "contact": {
        "email": "meltingmomentscakes@gmail.com",
        "phone": "+971 50 368 7757",
    },
    "seo": {
        "title": "سياسة الخصوصية",
        "description": "سياسة الخصوصية لملتينج مومنتس كيكس — كيف نجمع بياناتك الشخصية ونستخدمها ونحمي خصوصيتك.",
    },
}

PRIVACY_CONTENT = {"en": PRIVACY_EN, "ar": PRIVACY_AR}


def upgrade() -> None:
    conn = op.get_bind()
    now = datetime.utcnow()

    # Check if row already exists (idempotent)
    result = conn.execute(sa.text("SELECT id FROM cms_pages WHERE slug = 'privacy'"))
    if result.fetchone():
        # Update content if row already exists
        conn.execute(
            sa.text(
                "UPDATE cms_pages SET content = CAST(:content AS jsonb), updated_at = now() "
                "WHERE slug = 'privacy'"
            ),
            {"content": json.dumps(PRIVACY_CONTENT, ensure_ascii=False)},
        )
    else:
        conn.execute(
            sa.text(
                "INSERT INTO cms_pages (id, slug, is_active, content, created_at, updated_at) "
                "VALUES (CAST(:id AS uuid), :slug, :is_active, CAST(:content AS jsonb), :created_at, :updated_at)"
            ),
            {
                "id": str(uuid.uuid4()),
                "slug": "privacy",
                "is_active": True,
                "content": json.dumps(PRIVACY_CONTENT, ensure_ascii=False),
                "created_at": now,
                "updated_at": now,
            },
        )


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM cms_pages WHERE slug = 'privacy'"))
